import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import MainNav from "@/components/MainNav";
import SecondaryNav from "@/components/SecondaryNav";
import Footer from "@/components/Footer";

const getMontserrat = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${getMontserrat.variable} ${geistMono.variable} antialiased`}
      >
        <MainNav />
        <SecondaryNav />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
